version: "3.9"
services:
    ui:
        image: herodotus-cloud-ui:2.7.1.2
        build:
            context: ../context
            dockerfile: Dockerfile
        container_name: herodotus-cloud-ui
        ports:
            - "8888:8000"
